version: 2.1
jobs:
  build:
    docker:
      - image: cypress/included:latest

    working_directory: ~/project

    steps:
      - checkout

      # Install dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm install
            npx cypress install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npm run all-tests-report

      # Store HTML Reports as Artifacts
      - store_artifacts:
          path: reports

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^pull_request.*$ # Exclude PR events
            tags:
              ignore:
                - /.*/ # Exclude tag events
