version: 2.1
jobs:
  build:
    docker:
      - image: cypress/included:latest

    working_directory: ~/project

    steps:
      - checkout

      # Install dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npm run all-tests

      # Store HTML Reports as Artifacts
      - store_artifacts:
          path: reports

      # Optionally, clear reports, screenshots, and videos after tests
      - run:
          name: Clear Reports, Screenshots, and Videos
          command: npm run clear-reports

      # Optionally, save cache
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
