version: 2.1
jobs:
  build:
    docker:
      - image: cypress/included:latest

    working_directory: ~/project

    steps:
      - checkout

      # Install dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npm run all-tests-report

      # Store HTML Reports as Artifacts
      - store_artifacts:
          path: reports

      # Optionally, clear reports, screenshots, and videos after tests
      - run:
          name: Clear Reports, Screenshots, and Videos
          command: npm run clear-reports

      # Optionally, save cache
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Send Slack notification
      - run:
          name: Notify Slack
          command: |
            apt-get update && apt-get install -y curl
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Your build has completed."}' https://hooks.slack.com/services/T0560AKL4QJ/B0713dfd756VPT/7tyZbQaoLcBfdfvEJVybADpGux7

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
